name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 3.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.3.1
  quiver: ^3.1.0
  xml: ^6.1.0
  image: ^3.2.0
  collection: ^1.16.0

dev_dependencies:
  test: ^1.21.6
  path: ^1.8.2
  pedantic: ^1.11.0
